question_data = [{"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "In architecture, a &quot;pecklesteiner&quot; is a set of doors that overlap each other when closed, and can be locked through a single keyhole.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Nutella is produced by the German company Ferrero.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Slovakia is a member of European Union-",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Ping-Pong originated in England",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "French is an official language in Canada.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
                  "incorrect_answers": ["True"]}]
